### PR TITLE
Added info.md

### PR DESCRIPTION
**Pull request by Aditya-Pachauri**
Issue: #1

#### Short description of what this resolves:
This PR resolves the task by adding the info.md file with details about me, including my background, interests, and an answer to the task-related question.

#### Changes proposed in this pull request and/or Screenshots of changes:

- Added info.md file to the project.
- The file includes my details: academic information, hobbies (cricket and painting), and an answer to the machine learning-related question.

### CODE REVIEW

**Comment by Shivg2901** [comment]
@Aditya-Pachauri 
Task 2 isnt correct
You have to create seperate PR's for both issues

**Comment by Aditya-Pachauri** [comment]
I will complete it as soon as possible but what about issue 1

**Comment by Shivg2901** [comment]
@Aditya-Pachauri 
[Task-2/Aditya-Pachauri.txt](https://github.com/opencodeiiita/GoGit-4.0/pull/113/files#diff-f057d6f85fbd4f5d37e547347cc8f464efd6cbbe9136d4dc9e65facba73f680d)

remove this file and create a PR for issue

**Comment by Aditya-Pachauri** [comment]
Dear Sir,
I am unable to understand why should i remove the file i am just left with
merging branches than i will create PR for that issue

**Pull request closed without merging**
