### PR TITLE
Added info.md

### PR DESCRIPTION
**Pull request by ATGenZ**
Issue: #1 

Short description of what this resolves:
#14 

Changes proposed in this pull request and/or Screenshots of changes:

Added info.md file to the repo.
-
-
-

### CODE REVIEW

**Comment by shauryaaa100** [comment]
Please add the file at the proper location, as mentioned in the [CONTRIBUTING.md](.github/CONTRIBUTING.md) file. Also, follow the PR Template properly.

**Comment by ATGenZ** [comment]
Issue: #1 

Short description of what this resolves:
#14 

Changes proposed in this pull request and/or Screenshots of changes:
Added info.md file to the repo.

**Comment by Shivg2901** [comment]
@ATGenZ 
Why are you tagging #14 
Reopen the pr with proper template and description

**Comment by ATGenZ** [comment]
Issue: #1 

Short description of what this resolves:
Added my info in info.md.

Changes proposed in this pull request and/or Screenshots of changes:

Added info.md file to the repo.

**Pull request closed without merging**
